kind: pipeline
name: default

steps:
  - name: composer
    image: knik/php:7.3-fpm-stretch
    commands:
      - apt -y update && apt install -y git
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - composer install --no-ansi
      - touch composer_installed

  - name: npm
    image: node:20
    commands:
      - node --version
      - npm install
      - npm run prod

  - name: tests-php-7.3
    image: knik/php:7.3-fpm-stretch
    environment:
      APP_KEY: base64:QhlU2DzlLyaYVHzlh3RlSipTtBhwb3/5jPKbctx2lP8=
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: secret
    commands:
      - cp .env.example .env
      - php artisan migrate:fresh --seed
      - php artisan route:list
      - vendor/bin/phpunit --verbose
      - rm -rf storage/app/certs
      - rm -rf storage/framework/cache/data/*
      - rm -rf storage/framework/sessions/*
      - rm -rf storage/framework/views/*
      - rm -rf storage/debugbar/*
      - rm -rf storage/logs/*
      - rm .env

  - name: tests-php-7.4
    image: knik/php:7.4-fpm-alpine
    environment:
      APP_KEY: base64:QhlU2DzlLyaYVHzlh3RlSipTtBhwb3/5jPKbctx2lP8=
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: secret
    commands:
      - cp .env.example .env
      - php artisan migrate:fresh --seed
      - vendor/bin/phpunit --verbose
      - rm -rf storage/app/certs
      - rm -rf storage/framework/cache/data/*
      - rm -rf storage/framework/sessions/*
      - rm -rf storage/framework/views/*
      - rm -rf storage/debugbar/*
      - rm -rf storage/logs/*
      - rm .env

  - name: tests-php-8.0
    image: knik/php:8.0-fpm-alpine
    environment:
      APP_KEY: base64:QhlU2DzlLyaYVHzlh3RlSipTtBhwb3/5jPKbctx2lP8=
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: secret
    commands:
      - cp .env.example .env
      - php artisan migrate:fresh --seed
      - vendor/bin/phpunit --verbose
      - rm -rf storage/app/certs
      - rm -rf storage/framework/cache/data/*
      - rm -rf storage/framework/sessions/*
      - rm -rf storage/framework/views/*
      - rm -rf storage/debugbar/*
      - rm -rf storage/logs/*
      - rm .env

  - name: tests-php-8.1
    image: knik/php:8.1-fpm-alpine
    environment:
      APP_KEY: base64:QhlU2DzlLyaYVHzlh3RlSipTtBhwb3/5jPKbctx2lP8=
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: secret
    commands:
      - cp .env.example .env
      - php artisan migrate:fresh --seed
      - vendor/bin/phpunit --verbose
      - rm -rf storage/app/certs
      - rm -rf storage/framework/cache/data/*
      - rm -rf storage/framework/sessions/*
      - rm -rf storage/framework/views/*
      - rm -rf storage/debugbar/*
      - rm -rf storage/logs/*
      - rm .env

  - name: tests-php-8.2
    image: knik/php:8.2-fpm-alpine
    failure: ignore
    environment:
      APP_KEY: base64:QhlU2DzlLyaYVHzlh3RlSipTtBhwb3/5jPKbctx2lP8=
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: secret
    commands:
      - cp .env.example .env
      - php artisan migrate:fresh --seed
      - vendor/bin/phpunit --verbose
      - rm -rf storage/app/certs
      - rm -rf storage/framework/cache/data/*
      - rm -rf storage/framework/sessions/*
      - rm -rf storage/framework/views/*
      - rm -rf storage/debugbar/*
      - rm -rf storage/logs/*
      - rm .env

  - name: browser-tests
    image: knik/php:7.3-fpm-buster
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
      APP_KEY: base64:QhlU2DzlLyaYVHzlh3RlSipTtBhwb3/5jPKbctx2lP8=
      APP_DEBUG: true
      APP_ENV: local
      APP_ALLOW_REGISTRATION: true
      APP_TIMEZONE: UTC
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: secret
      APP_URL: http://webserver
      DAEMON_SETUP_TOKEN: test_auto_setup_token
      CACHE_DRIVER: null
    commands:
      - ./artisan migrate:fresh --seed
      - ./artisan dusk --debug --exclude-group daemon,userServers
      - ./artisan migrate:fresh --seed
      - ./artisan dusk --debug --group daemon
      - rm -rf storage/app/certs
      - rm -rf storage/framework/cache/data/*
      - rm -rf storage/framework/sessions/*
      - rm -rf storage/framework/views/*
      - rm -rf storage/debugbar/*
      - rm -rf storage/logs/*
    shm_size: 2000000000
    volumes:
      - name: daemon_logs
        path: /var/log/gameap-daemon

  - name: composer-production
    image: knik/php:7.3-fpm-stretch
    commands:
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - composer install --no-dev --optimize-autoloader --no-ansi
      - rm composer_installed
    when:
      branch:
        - master

  - name: archive
    image: debian:buster
    commands:
      - apt update && apt -y install rsync
      - mkdir gameap
      - rsync -rl --exclude=/gameap --exclude=/node_modules --exclude=/storage/app/certs ./ gameap/
      - tar czf "/publish/gameap-3.1.tar.gz" "gameap"
    volumes:
      - name: publish
        path: /publish
    when:
      branch:
        - master
        - aws-publish-test

  - name: archive-shared
    image: knik/php:8.2-fpm-alpine
    environment:
      APP_KEY: base64:QhlU2DzlLyaYVHzlh3RlSipTtBhwb3/5jPKbctx2lP8=
      APP_DEBUG: true
      APP_ENV: local
      APP_ALLOW_REGISTRATION: true
      APP_TIMEZONE: UTC
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: secret
      APP_URL: http://webserver
    commands:
      - apk add mariadb-client zip unzip rsync
      - rm -rf storage/app/certs/*
      - rm -rf storage/framework/cache/data/*
      - rm -rf storage/framework/sessions/*
      - rm -rf storage/framework/views/*
      - rm -rf storage/debugbar/*
      - rm -rf storage/logs/*
      - rm .env || true
      - mkdir -p gameap-shared/upload
      - php artisan migrate:fresh --seed --force
      - mysqldump -h db -u homestead -p --password=secret homestead > gameap.sql
      - curl -O http://packages.gameap.com/gameap/shared-build-artifacts.zip
      - rsync -rl --exclude=/gameap --exclude=/node_modules --exclude=/storage/app/certs --exclude=/publish --exclude=/shared-build-artifacts.zip ./ gameap-shared/upload/
      - unzip -o shared-build-artifacts.zip -d gameap-shared
      - cd gameap-shared
        && mv upload/gameap.sql gameap.sql
        && zip -r "/publish/gameap-3.1-shared.zip" ./
    volumes:
      - name: publish
        path: /publish
    when:
      branch:
        - master
        - aws-publish-test

  - name: publish
    image: cschlosser/drone-ftps
    environment:
      FTP_USERNAME:
        from_secret: ftp_username
      FTP_PASSWORD:
        from_secret: ftp_password
    settings:
      hostname: packages.gameap.ru:21
      secrets: [ ftp_username, ftp_password ]
      secure: false
      src_dir: /publish
      dest_dir: /gameap
      chmod: false
      include:
        - ^.*tar\.gz$
        - ^.*zip$
    volumes:
      - name: publish
        path: /drone/src/publish
    when:
      branch:
        - master
        - aws-publish-test

  - name: publish-sdn
    image: plugins/s3
    settings:
      bucket: gameap
      region: eu-central-1
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      source: /publish/*
      strip_prefix: /publish
      target: /gameap
    volumes:
      - name: publish
        path: /publish
    when:
      branch:
        - master
        - aws-publish-test

  - name: artifacts
    image: knik/drone-s3-plugin
    failure: ignore
    settings:
      endpoint:
        from_secret: s3_endpoint
      bucket: gameap-drone-tests
      access_key:
        from_secret: s3_access_key
      secret_key:
        from_secret: s3_secret_key
      source:
        - tests/Browser/screenshots/*
        - tests/Browser/console/*
        - storage/logs/*
        - /var/log/gameap-daemon/*
      target: /${DRONE_BRANCH}/${DRONE_BUILD_NUMBER}
      path_style: true
    volumes:
      - name: daemon_logs
        path: /var/log/gameap-daemon
    when:
      status:
        - failure

services:
  - name: db
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: userpass
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret

  - name: webserver
    image: knik/php:7.4-cli-alpine
    environment:
      APP_KEY: base64:QhlU2DzlLyaYVHzlh3RlSipTtBhwb3/5jPKbctx2lP8=
      APP_DEBUG: true
      APP_ENV: local
      APP_ALLOW_REGISTRATION: true
      APP_TIMEZONE: UTC
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: secret
      CACHE_DRIVER: null
    commands:
      - while [[ ! -f composer_installed ]]; do sleep 2; echo "Waiting composer..."; done;
      - ./artisan serve --host=webserver --port=80

  - name: selenium
    image: selenium/standalone-chrome:4.1.0
    shm_size: 2000000000
    environment:
      HUB_PORT: 4444
      SCREEN_WIDTH: 1280
      SCREEN_HEIGHT: 800

volumes:
  - name: daemon_logs
    temp: {}

  - name: publish
    temp: {}